abi = [
    {"inputs": [], "stateMutability": "nonpayable", "type": "constructor"},
    {"stateMutability": "payable", "type": "fallback"},
    {"inputs": [{"internalType": "string", "name": "gid", "type": "string"}], "name": "cancelGame", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
    {
        "inputs": [{"internalType": "string", "name": "gid", "type": "string"}, {"internalType": "uint256", "name": "wager", "type": "uint256"}],
        "name": "createGame",
        "outputs": [],
        "stateMutability": "payable",
        "type": "function",
    },
    {"inputs": [{"internalType": "string", "name": "gid", "type": "string"}], "name": "declareDraw", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
    {
        "inputs": [{"internalType": "string", "name": "gid", "type": "string"}, {"internalType": "address", "name": "_winner", "type": "address"}],
        "name": "declareWinner",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {"inputs": [], "name": "getCommissionPercentage", "outputs": [{"internalType": "uint32", "name": "", "type": "uint32"}], "stateMutability": "view", "type": "function"},
    {"inputs": [], "name": "getContractBalance", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"},
    {"inputs": [], "name": "isPaused", "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "view", "type": "function"},
    {"inputs": [{"internalType": "string", "name": "gid", "type": "string"}], "name": "joinGame", "outputs": [], "stateMutability": "payable", "type": "function"},
    {"inputs": [{"internalType": "uint32", "name": "commission", "type": "uint32"}], "name": "setCommissionPercentage", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
    {"inputs": [], "name": "togglePause", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
    {"inputs": [{"internalType": "uint256", "name": "withdrawalAmount", "type": "uint256"}], "name": "withdraw", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
    {"stateMutability": "payable", "type": "receive"},
]
