# general
DECISECONDS_PER_MINUTE = 600
CONCURRENT_GAME_LIMIT = 100

# game outcomes
TIMEOUT = 11
RESIGNATION = 12
AGREEMENT = 13

# rate limiting
BUCKET_CAPACITY = 100
INITIAL_TOKENS = 20
REFILL_RATE_MINUTE = 4
